name: Secrets Check

on: [push]

jobs:
  trivy-secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      

      - name: Install Trivy
        run: |
          wget -O ./trivy.deb https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb
          sudo dpkg -i ./trivy.deb 
          trivy -v

      - name: Trivy Secrets Check
        run: |
          export files=$(find ./ -type d -not -path '*.git*')
          export check="secret"
          ./.github/workflows/trivy_check.sh

      - name: Slack Notification
        if: ${{ failure() }}
        uses: lazy-actions/slatify@v3.0.0
        with:
          type: ${{ job.status }}
          url: ${{ secrets.SLACK_INFRA_WEBHOOK }}
          job_name: '*Secrets vulnerabilities on repo marketing_mix_modeling*'
          channel: '#team-infra'
